<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health_coach_call.proto

namespace GPBMetadata\HealthCoachCall;

class HealthCoachCall
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xDD\x06\x0A\x17health_coach_call.proto\x12\x11health_coach_call\"8\x0A\x17HealthCoachCallResponse\x12\x0F\x0A\x07message\x18\x01 \x01(\x09\x12\x0C\x0A\x04code\x18\x02 \x01(\x05\"\xF2\x02\x0A\x0BCallRequest\x12\x17\x0A\x0Fhealth_coach_id\x18\x01 \x01(\x03\x12\x11\x0A\x09call_time\x18\x02 \x01(\x03\x12\x11\x0A\x09call_type\x18\x03 \x01(\x09\x12\x14\x0A\x0Ccall_purpose\x18\x04 \x01(\x09\x12\x0F\x0A\x07user_id\x18\x05 \x01(\x03\x12\x11\x0A\x09user_type\x18\x06 \x01(\x05\x12\x18\x0A\x10schedule_call_id\x18\x07 \x01(\x03\x12\x16\x0A\x0Erequest_source\x18\x08 \x01(\x09\x12\x14\x0A\x0Cproject_name\x18\x09 \x01(\x09\x12\x12\x0A\x0Acreated_by\x18\x0A \x01(\x09\x12\x12\x0A\x0Aupdated_by\x18\x0B \x01(\x09\x12\x0E\x0A\x06status\x18\x0C \x01(\x05\x12\x18\x0A\x10internal_remarks\x18\x0D \x01(\x09\x12\x18\x0A\x10customer_remarks\x18\x0E \x01(\x09\x12\x13\x0A\x0Bcall_source\x18\x0F \x01(\x09\x12!\x0A\x19is_new_fitfeast_dashboard\x18\x10 \x01(\x082\xAD\x02\x0A\x0FHealthCoachCall\x12\\\x0A\x0CScheduleCall\x12\x1E.health_coach_call.CallRequest\x1A*.health_coach_call.HealthCoachCallResponse\"\x00\x12Z\x0A\x0ACancelCall\x12\x1E.health_coach_call.CallRequest\x1A*.health_coach_call.HealthCoachCallResponse\"\x00\x12`\x0A\x10UpdateCallStatus\x12\x1E.health_coach_call.CallRequest\x1A*.health_coach_call.HealthCoachCallResponse\"\x00BHZ\x16protos/healthCoachCall\xCA\x02\x0FHealthCoachCall\xE2\x02\x1BGPBMetadata\\HealthCoachCallb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

