<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fitfeast_communication.proto

namespace GPBMetadata\FitfeastCommunication;

class FitfeastCommunication
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xFB\x03\x0A\x1Cfitfeast_communication.proto\x12\x16fitfeast_communication\"\xA4\x01\x0A%CustomerDietAssignNotificationRequest\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x03\x12\x15\x0A\x0Dtemplate_type\x18\x02 \x01(\x09\x12\x19\x0A\x11last_date_of_diet\x18\x03 \x01(\x09\x12\x15\x0A\x0Ddiet_token_id\x18\x04 \x01(\x09\x12!\x0A\x19is_new_fitfeast_dashboard\x18\x05 \x01(\x08\"\x1B\x0A\x08Response\x12\x0F\x0A\x07message\x18\x01 \x01(\x092\x99\x01\x0A\x1CFitfeastCommunicationService\x12y\x0A\x16DietAssignNotification\x12=.fitfeast_communication.CustomerDietAssignNotificationRequest\x1A .fitfeast_communication.ResponseB[Z\x1Dprotos/fitfeast_communication\xCA\x02\x15FitfeastCommunication\xE2\x02!GPBMetadata\\FitfeastCommunicationb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

