<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health_coach_call.proto

namespace HealthCoachCall;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>health_coach_call.CallRequest</code>
 */
class CallRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 health_coach_id = 1;</code>
     */
    protected $health_coach_id = 0;
    /**
     * Generated from protobuf field <code>int64 call_time = 2;</code>
     */
    protected $call_time = 0;
    /**
     * Generated from protobuf field <code>string call_type = 3;</code>
     */
    protected $call_type = '';
    /**
     * Generated from protobuf field <code>string call_purpose = 4;</code>
     */
    protected $call_purpose = '';
    /**
     * Generated from protobuf field <code>int64 user_id = 5;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>int32 user_type = 6;</code>
     */
    protected $user_type = 0;
    /**
     * Generated from protobuf field <code>int64 schedule_call_id = 7;</code>
     */
    protected $schedule_call_id = 0;
    /**
     * Generated from protobuf field <code>string request_source = 8;</code>
     */
    protected $request_source = '';
    /**
     * Generated from protobuf field <code>string project_name = 9;</code>
     */
    protected $project_name = '';
    /**
     * Generated from protobuf field <code>string created_by = 10;</code>
     */
    protected $created_by = '';
    /**
     * Generated from protobuf field <code>string updated_by = 11;</code>
     */
    protected $updated_by = '';
    /**
     * Generated from protobuf field <code>int32 status = 12;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string internal_remarks = 13;</code>
     */
    protected $internal_remarks = '';
    /**
     * Generated from protobuf field <code>string customer_remarks = 14;</code>
     */
    protected $customer_remarks = '';
    /**
     * Generated from protobuf field <code>string call_source = 15;</code>
     */
    protected $call_source = '';
    /**
     * Generated from protobuf field <code>bool is_new_fitfeast_dashboard = 16;</code>
     */
    protected $is_new_fitfeast_dashboard = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $health_coach_id
     *     @type int|string $call_time
     *     @type string $call_type
     *     @type string $call_purpose
     *     @type int|string $user_id
     *     @type int $user_type
     *     @type int|string $schedule_call_id
     *     @type string $request_source
     *     @type string $project_name
     *     @type string $created_by
     *     @type string $updated_by
     *     @type int $status
     *     @type string $internal_remarks
     *     @type string $customer_remarks
     *     @type string $call_source
     *     @type bool $is_new_fitfeast_dashboard
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\HealthCoachCall\HealthCoachCall::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 health_coach_id = 1;</code>
     * @return int|string
     */
    public function getHealthCoachId()
    {
        return $this->health_coach_id;
    }

    /**
     * Generated from protobuf field <code>int64 health_coach_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHealthCoachId($var)
    {
        GPBUtil::checkInt64($var);
        $this->health_coach_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 call_time = 2;</code>
     * @return int|string
     */
    public function getCallTime()
    {
        return $this->call_time;
    }

    /**
     * Generated from protobuf field <code>int64 call_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCallTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->call_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string call_type = 3;</code>
     * @return string
     */
    public function getCallType()
    {
        return $this->call_type;
    }

    /**
     * Generated from protobuf field <code>string call_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCallType($var)
    {
        GPBUtil::checkString($var, True);
        $this->call_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string call_purpose = 4;</code>
     * @return string
     */
    public function getCallPurpose()
    {
        return $this->call_purpose;
    }

    /**
     * Generated from protobuf field <code>string call_purpose = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCallPurpose($var)
    {
        GPBUtil::checkString($var, True);
        $this->call_purpose = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 5;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 user_type = 6;</code>
     * @return int
     */
    public function getUserType()
    {
        return $this->user_type;
    }

    /**
     * Generated from protobuf field <code>int32 user_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkInt32($var);
        $this->user_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 schedule_call_id = 7;</code>
     * @return int|string
     */
    public function getScheduleCallId()
    {
        return $this->schedule_call_id;
    }

    /**
     * Generated from protobuf field <code>int64 schedule_call_id = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScheduleCallId($var)
    {
        GPBUtil::checkInt64($var);
        $this->schedule_call_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string request_source = 8;</code>
     * @return string
     */
    public function getRequestSource()
    {
        return $this->request_source;
    }

    /**
     * Generated from protobuf field <code>string request_source = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string project_name = 9;</code>
     * @return string
     */
    public function getProjectName()
    {
        return $this->project_name;
    }

    /**
     * Generated from protobuf field <code>string project_name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setProjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_by = 10;</code>
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Generated from protobuf field <code>string created_by = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_by = 11;</code>
     * @return string
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Generated from protobuf field <code>string updated_by = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 12;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string internal_remarks = 13;</code>
     * @return string
     */
    public function getInternalRemarks()
    {
        return $this->internal_remarks;
    }

    /**
     * Generated from protobuf field <code>string internal_remarks = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setInternalRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->internal_remarks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_remarks = 14;</code>
     * @return string
     */
    public function getCustomerRemarks()
    {
        return $this->customer_remarks;
    }

    /**
     * Generated from protobuf field <code>string customer_remarks = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_remarks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string call_source = 15;</code>
     * @return string
     */
    public function getCallSource()
    {
        return $this->call_source;
    }

    /**
     * Generated from protobuf field <code>string call_source = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setCallSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->call_source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_new_fitfeast_dashboard = 16;</code>
     * @return bool
     */
    public function getIsNewFitfeastDashboard()
    {
        return $this->is_new_fitfeast_dashboard;
    }

    /**
     * Generated from protobuf field <code>bool is_new_fitfeast_dashboard = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNewFitfeastDashboard($var)
    {
        GPBUtil::checkBool($var);
        $this->is_new_fitfeast_dashboard = $var;

        return $this;
    }

}

