<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fitfeast_communication.proto

namespace FitfeastCommunication;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>fitfeast_communication.CustomerDietAssignNotificationRequest</code>
 */
class CustomerDietAssignNotificationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>string template_type = 2;</code>
     */
    protected $template_type = '';
    /**
     * Generated from protobuf field <code>string last_date_of_diet = 3;</code>
     */
    protected $last_date_of_diet = '';
    /**
     * Generated from protobuf field <code>string diet_token_id = 4;</code>
     */
    protected $diet_token_id = '';
    /**
     * Generated from protobuf field <code>bool is_new_fitfeast_dashboard = 5;</code>
     */
    protected $is_new_fitfeast_dashboard = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type string $template_type
     *     @type string $last_date_of_diet
     *     @type string $diet_token_id
     *     @type bool $is_new_fitfeast_dashboard
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FitfeastCommunication\FitfeastCommunication::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string template_type = 2;</code>
     * @return string
     */
    public function getTemplateType()
    {
        return $this->template_type;
    }

    /**
     * Generated from protobuf field <code>string template_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateType($var)
    {
        GPBUtil::checkString($var, True);
        $this->template_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_date_of_diet = 3;</code>
     * @return string
     */
    public function getLastDateOfDiet()
    {
        return $this->last_date_of_diet;
    }

    /**
     * Generated from protobuf field <code>string last_date_of_diet = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLastDateOfDiet($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_date_of_diet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string diet_token_id = 4;</code>
     * @return string
     */
    public function getDietTokenId()
    {
        return $this->diet_token_id;
    }

    /**
     * Generated from protobuf field <code>string diet_token_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDietTokenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->diet_token_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_new_fitfeast_dashboard = 5;</code>
     * @return bool
     */
    public function getIsNewFitfeastDashboard()
    {
        return $this->is_new_fitfeast_dashboard;
    }

    /**
     * Generated from protobuf field <code>bool is_new_fitfeast_dashboard = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNewFitfeastDashboard($var)
    {
        GPBUtil::checkBool($var);
        $this->is_new_fitfeast_dashboard = $var;

        return $this;
    }

}

