<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: latest_blogs.proto

namespace LatestBlogs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>latest_blogs.Blog</code>
 */
class Blog extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string blog_title = 1;</code>
     */
    protected $blog_title = '';
    /**
     * Generated from protobuf field <code>string short_content = 2;</code>
     */
    protected $short_content = '';
    /**
     * Generated from protobuf field <code>string publish_date = 3;</code>
     */
    protected $publish_date = '';
    /**
     * Generated from protobuf field <code>string update_time = 4;</code>
     */
    protected $update_time = '';
    /**
     * Generated from protobuf field <code>string create_time = 5;</code>
     */
    protected $create_time = '';
    /**
     * Generated from protobuf field <code>string seo_url = 6;</code>
     */
    protected $seo_url = '';
    /**
     * Generated from protobuf field <code>int32 team_member_id = 7;</code>
     */
    protected $team_member_id = 0;
    /**
     * Generated from protobuf field <code>string published_by = 8;</code>
     */
    protected $published_by = '';
    /**
     * Generated from protobuf field <code>string banner_image = 9;</code>
     */
    protected $banner_image = '';
    /**
     * Generated from protobuf field <code>string blog_type = 10;</code>
     */
    protected $blog_type = '';
    /**
     * Generated from protobuf field <code>string publisher_photo = 11;</code>
     */
    protected $publisher_photo = '';
    /**
     * Generated from protobuf field <code>string author_url = 12;</code>
     */
    protected $author_url = '';
    /**
     * Generated from protobuf field <code>string original_seo_url = 13;</code>
     */
    protected $original_seo_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $blog_title
     *     @type string $short_content
     *     @type string $publish_date
     *     @type string $update_time
     *     @type string $create_time
     *     @type string $seo_url
     *     @type int $team_member_id
     *     @type string $published_by
     *     @type string $banner_image
     *     @type string $blog_type
     *     @type string $publisher_photo
     *     @type string $author_url
     *     @type string $original_seo_url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LatestBlogs\LatestBlogs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string blog_title = 1;</code>
     * @return string
     */
    public function getBlogTitle()
    {
        return $this->blog_title;
    }

    /**
     * Generated from protobuf field <code>string blog_title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBlogTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->blog_title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string short_content = 2;</code>
     * @return string
     */
    public function getShortContent()
    {
        return $this->short_content;
    }

    /**
     * Generated from protobuf field <code>string short_content = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShortContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->short_content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string publish_date = 3;</code>
     * @return string
     */
    public function getPublishDate()
    {
        return $this->publish_date;
    }

    /**
     * Generated from protobuf field <code>string publish_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPublishDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->publish_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string update_time = 4;</code>
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Generated from protobuf field <code>string update_time = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string create_time = 5;</code>
     * @return string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>string create_time = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string seo_url = 6;</code>
     * @return string
     */
    public function getSeoUrl()
    {
        return $this->seo_url;
    }

    /**
     * Generated from protobuf field <code>string seo_url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSeoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->seo_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 team_member_id = 7;</code>
     * @return int
     */
    public function getTeamMemberId()
    {
        return $this->team_member_id;
    }

    /**
     * Generated from protobuf field <code>int32 team_member_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTeamMemberId($var)
    {
        GPBUtil::checkInt32($var);
        $this->team_member_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string published_by = 8;</code>
     * @return string
     */
    public function getPublishedBy()
    {
        return $this->published_by;
    }

    /**
     * Generated from protobuf field <code>string published_by = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPublishedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->published_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string banner_image = 9;</code>
     * @return string
     */
    public function getBannerImage()
    {
        return $this->banner_image;
    }

    /**
     * Generated from protobuf field <code>string banner_image = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setBannerImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->banner_image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string blog_type = 10;</code>
     * @return string
     */
    public function getBlogType()
    {
        return $this->blog_type;
    }

    /**
     * Generated from protobuf field <code>string blog_type = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setBlogType($var)
    {
        GPBUtil::checkString($var, True);
        $this->blog_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string publisher_photo = 11;</code>
     * @return string
     */
    public function getPublisherPhoto()
    {
        return $this->publisher_photo;
    }

    /**
     * Generated from protobuf field <code>string publisher_photo = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisherPhoto($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher_photo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string author_url = 12;</code>
     * @return string
     */
    public function getAuthorUrl()
    {
        return $this->author_url;
    }

    /**
     * Generated from protobuf field <code>string author_url = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->author_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string original_seo_url = 13;</code>
     * @return string
     */
    public function getOriginalSeoUrl()
    {
        return $this->original_seo_url;
    }

    /**
     * Generated from protobuf field <code>string original_seo_url = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalSeoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->original_seo_url = $var;

        return $this;
    }

}

