<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: latest_blogs.proto

namespace LatestBlogs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>latest_blogs.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>int32 code = 2;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>repeated .latest_blogs.Blog blogs = 3;</code>
     */
    private $blogs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *     @type int $code
     *     @type \LatestBlogs\Blog[] $blogs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LatestBlogs\LatestBlogs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 code = 2;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int32 code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .latest_blogs.Blog blogs = 3;</code>
     * @return RepeatedField<\LatestBlogs\Blog>
     */
    public function getBlogs()
    {
        return $this->blogs;
    }

    /**
     * Generated from protobuf field <code>repeated .latest_blogs.Blog blogs = 3;</code>
     * @param \LatestBlogs\Blog[] $var
     * @return $this
     */
    public function setBlogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LatestBlogs\Blog::class);
        $this->blogs = $arr;

        return $this;
    }

}

